---
src:
   endpoint: jp-east-2.os.cloud.nifty.com
   bucketname: 
   access_key:
   secret_key:
   headers:
      - cache-control: :cache_control
      - content-type: :content_type
dst:
   endpoint: jp-west-1.os.cloud.nifty.com
   bucketname:
   access_key:
   secret_key:
